# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = "Compute example app"
language = "javascript"
manifest_version = 2
name = "middleware-example"
service_id = ""
